
version: '3.8'

services:
  ai-model-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - AI_MODEL_SERVER_HOST=0.0.0.0
      - AI_MODEL_SERVER_PORT=8000
      - AI_MODEL_LOG_LEVEL=INFO
      - AI_MODEL_CACHE_ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis_data:
